Messages:
  Admin:
    ArenaNameExists: 'This name is already taken'
    NotEdittingArena: 'Not currently editting any arenas'
    NotFinishedEditting: 'Please finish setting up all spawn points before saving'
    ArenaCreateSuccess: 'Successfully created the arena'
    ArenaNotFound: 'Arena not found'
    PleaseCompleteArena: 'Please complete all of the arena before saving'
    ArenaUpdateSuccess: 'Successfully Updated the area'
    CancelAreaEdit: 'Canceled arena editor'
    SuccessRemoveArena: 'Successfully removed arena'
    Spawn1Set: 'Spawn 1 Successfully Set'
    Spawn2Set: 'Spawn 2 Successfully Set'
    StartedUpdatingArena: 'Started updating arena $1'
    StartedCreatingArena: 'Started creating new arena'
  Player:
    SendToSelf: 'Cannot send a duel request to yourself.' 
    RequestExists: 'A duel request between you two already exists.'
    NoAvailableArenas: 'Sorry there are no arenas currently available.'
    RequestNotExists: 'No request exists between you and that player.'
    InvalidCommand: 'Invalid Command'
    PlayerNotOnline: 'The specified player is not currently online'
    SendDuelRequest: '$1 has sent you a duel request. type "/duel accept $1" to accept'
    DuelLoading: 'You will be transported to the arena in $1 seconds. Move to cancel.'
    SendDuelSent: 'Your request has been sent'
    NotInArena: 'You are not currently in an arena'
    PlayerCanceledDuel: 'Player: $1, has canceled the duel by moving'
  Title:
    SendCountdown: 'Duel will begin in $1 seconds...'
    DuelStarted: 'Match has begun! You have $1 seconds to defeat your oponent.'
    DuelWon: 'Congratulations you won the duel! You have $1 seconds to collect the loot...'
    DuelLost: 'Duel lost...'
    OutOfTime: 'The duel is a draw! You have run out of time.'