Settings:
  DuelTime: 120 #seconds
  LootTime: 15 #seconds
  WarmupTime: 3 #seconds
  RequestLife: 30 #seconds
Messages:
  Admin:
    ArenaNameExists: '&4This name is already taken'
    NotEdittingArena: '&4Not currently editting any arenas'
    NotFinishedEditting: '&4Please finish setting up all spawn points before saving'
    ArenaCreateSuccess: '&2Successfully created the arena'
    ArenaNotFound: '&4Arena not found'
    PleaseCompleteArena: '&4Please complete all of the arena before saving'
    ArenaUpdateSuccess: '&2Successfully Updated the area'
    CancelAreaEdit: '&6Canceled arena editor'
    SuccessRemoveArena: '&2Successfully removed arena'
    Spawn1Set: '&2Spawn 1 Successfully Set'
    Spawn2Set: '&2Spawn 2 Successfully Set'
    StartedUpdatingArena: '&6Started updating arena $1'
    StartedCreatingArena: '&6Started creating new arena'
  Player:
    SendToSelf: '&4Cannot send a duel request to yourself.' 
    RequestExists: '&4A duel request between you two already exists.'
    NoAvailableArenas: '&6Sorry there are no arenas currently available.'
    RequestNotExists: '&4No request exists between you and that player.'
    InvalidCommand: '&4Duels Invalid Command'
    PlayerNotOnline: '&6The specified player is not currently online'
    SendDuelRequest: '&b$1 has sent you a duel request. type "/duel accept $1" to accept'
    DuelLoading: '&6You will be transported to the arena in $1 seconds. Move to cancel.'
    SendDuelSent: '&6Your request has been sent'
    NotInArena: '&4You are not currently in an arena'
    PlayerCanceledDuel: '&4Player: $1, has canceled the duel by moving'
    SendLeaveEarly: '&6You have decided to leave the arena early.'
  Title:
    SendCountdown: '&6Duel will begin in $1 seconds...'
    DuelStarted: '&6Match has begun! You have $1 seconds to defeat your oponent.'
    DuelWon: '&6Congratulations you won the duel! You have $1 seconds to collect the loot...'
    DuelLost: '&6Duel lost...'
    OutOfTime: '&6The duel is a draw! You have run out of time.'